/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.11.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *gameTable;
    QLabel *gameName;
    QTabWidget *roundTable;
    QWidget *start_page;
    QLabel *label;
    QLineEdit *lineEditRead;
    QPushButton *dialogReadButton;
    QPushButton *readButton;
    QWidget *simpleGame;
    QPushButton *pushButton_1_4;
    QLabel *question_1_5;
    QLabel *question_1_4;
    QPushButton *pushButton_1_1;
    QLabel *question_1_1;
    QPushButton *pushButton_1_5;
    QLabel *question_1_2;
    QPushButton *pushButton_1_6;
    QLabel *question_1_3;
    QLabel *question_1_6;
    QPushButton *pushButton_1_2;
    QPushButton *pushButton_1_3;
    QPushButton *wrongButton_1_1;
    QPushButton *wrongButton_1_2;
    QPushButton *wrongButton_1_3;
    QPushButton *wrongButton_1_4;
    QPushButton *wrongButton_1_5;
    QPushButton *wrongButton_1_6;
    QWidget *dubleGame;
    QLabel *question_2_6;
    QPushButton *pushButton_2_4;
    QPushButton *wrongButton_2_4;
    QPushButton *pushButton_2_6;
    QPushButton *pushButton_2_2;
    QPushButton *wrongButton_2_5;
    QPushButton *pushButton_2_1;
    QLabel *question_2_5;
    QLabel *question_2_4;
    QPushButton *wrongButton_2_6;
    QPushButton *wrongButton_2_1;
    QPushButton *pushButton_2_3;
    QLabel *question_2_1;
    QLabel *question_2_3;
    QPushButton *wrongButton_2_2;
    QPushButton *wrongButton_2_3;
    QLabel *question_2_2;
    QPushButton *pushButton_2_5;
    QWidget *tripleGame;
    QLabel *question_3_6;
    QPushButton *pushButton_3_4;
    QPushButton *wrongButton_3_4;
    QPushButton *pushButton_3_6;
    QPushButton *pushButton_3_2;
    QPushButton *wrongButton_3_5;
    QPushButton *pushButton_3_1;
    QLabel *question_3_5;
    QLabel *question_3_4;
    QPushButton *wrongButton_3_6;
    QPushButton *wrongButton_3_1;
    QPushButton *pushButton_3_3;
    QLabel *question_3_1;
    QLabel *question_3_3;
    QPushButton *wrongButton_3_2;
    QPushButton *wrongButton_3_3;
    QLabel *question_3_2;
    QPushButton *pushButton_3_5;
    QWidget *reversGame;
    QLabel *question_4_6;
    QPushButton *pushButton_4_4;
    QPushButton *wrongButton_4_4;
    QPushButton *pushButton_4_6;
    QPushButton *pushButton_4_2;
    QPushButton *wrongButton_4_5;
    QPushButton *pushButton_4_1;
    QLabel *question_4_5;
    QLabel *question_4_4;
    QPushButton *wrongButton_4_6;
    QPushButton *wrongButton_4_1;
    QPushButton *pushButton_4_3;
    QLabel *question_4_1;
    QLabel *question_4_3;
    QPushButton *wrongButton_4_2;
    QPushButton *wrongButton_4_3;
    QLabel *question_4_2;
    QPushButton *pushButton_4_5;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(800, 500);
        MainWindow->setMinimumSize(QSize(800, 500));
        gameTable = new QWidget(MainWindow);
        gameTable->setObjectName(QStringLiteral("gameTable"));
        gameTable->setMinimumSize(QSize(800, 500));
        gameName = new QLabel(gameTable);
        gameName->setObjectName(QStringLiteral("gameName"));
        gameName->setEnabled(true);
        gameName->setGeometry(QRect(170, 30, 441, 61));
        gameName->setMinimumSize(QSize(441, 31));
        QFont font;
        font.setPointSize(24);
        gameName->setFont(font);
        gameName->setAlignment(Qt::AlignCenter);
        roundTable = new QTabWidget(gameTable);
        roundTable->setObjectName(QStringLiteral("roundTable"));
        roundTable->setGeometry(QRect(70, 90, 631, 401));
        roundTable->setTabPosition(QTabWidget::East);
        start_page = new QWidget();
        start_page->setObjectName(QStringLiteral("start_page"));
        label = new QLabel(start_page);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 60, 131, 31));
        lineEditRead = new QLineEdit(start_page);
        lineEditRead->setObjectName(QStringLiteral("lineEditRead"));
        lineEditRead->setGeometry(QRect(140, 60, 301, 31));
        dialogReadButton = new QPushButton(start_page);
        dialogReadButton->setObjectName(QStringLiteral("dialogReadButton"));
        dialogReadButton->setGeometry(QRect(450, 40, 101, 31));
        readButton = new QPushButton(start_page);
        readButton->setObjectName(QStringLiteral("readButton"));
        readButton->setGeometry(QRect(450, 80, 101, 31));
        roundTable->addTab(start_page, QString());
        simpleGame = new QWidget();
        simpleGame->setObjectName(QStringLiteral("simpleGame"));
        pushButton_1_4 = new QPushButton(simpleGame);
        pushButton_1_4->setObjectName(QStringLiteral("pushButton_1_4"));
        pushButton_1_4->setGeometry(QRect(180, 200, 271, 31));
        pushButton_1_4->setMinimumSize(QSize(231, 21));
        QFont font1;
        font1.setPointSize(14);
        pushButton_1_4->setFont(font1);
        question_1_5 = new QLabel(simpleGame);
        question_1_5->setObjectName(QStringLiteral("question_1_5"));
        question_1_5->setEnabled(true);
        question_1_5->setGeometry(QRect(171, 250, 291, 51));
        question_1_5->setMinimumSize(QSize(251, 31));
        question_1_5->setMouseTracking(true);
        question_1_5->setFrameShape(QFrame::Panel);
        question_1_5->setLineWidth(2);
        question_1_5->setMidLineWidth(1);
        question_1_5->setAlignment(Qt::AlignCenter);
        question_1_4 = new QLabel(simpleGame);
        question_1_4->setObjectName(QStringLiteral("question_1_4"));
        question_1_4->setEnabled(true);
        question_1_4->setGeometry(QRect(171, 190, 291, 51));
        question_1_4->setMinimumSize(QSize(251, 31));
        question_1_4->setMouseTracking(true);
        question_1_4->setFrameShape(QFrame::Panel);
        question_1_4->setLineWidth(2);
        question_1_4->setMidLineWidth(1);
        question_1_4->setAlignment(Qt::AlignCenter);
        pushButton_1_1 = new QPushButton(simpleGame);
        pushButton_1_1->setObjectName(QStringLiteral("pushButton_1_1"));
        pushButton_1_1->setGeometry(QRect(179, 20, 271, 31));
        pushButton_1_1->setMinimumSize(QSize(231, 21));
        pushButton_1_1->setFont(font1);
        question_1_1 = new QLabel(simpleGame);
        question_1_1->setObjectName(QStringLiteral("question_1_1"));
        question_1_1->setEnabled(true);
        question_1_1->setGeometry(QRect(170, 10, 291, 51));
        question_1_1->setMinimumSize(QSize(251, 31));
        question_1_1->setMouseTracking(true);
        question_1_1->setFrameShape(QFrame::Panel);
        question_1_1->setLineWidth(2);
        question_1_1->setMidLineWidth(1);
        question_1_1->setAlignment(Qt::AlignCenter);
        pushButton_1_5 = new QPushButton(simpleGame);
        pushButton_1_5->setObjectName(QStringLiteral("pushButton_1_5"));
        pushButton_1_5->setGeometry(QRect(180, 260, 271, 31));
        pushButton_1_5->setMinimumSize(QSize(231, 21));
        pushButton_1_5->setFont(font1);
        question_1_2 = new QLabel(simpleGame);
        question_1_2->setObjectName(QStringLiteral("question_1_2"));
        question_1_2->setEnabled(true);
        question_1_2->setGeometry(QRect(170, 70, 291, 51));
        question_1_2->setMinimumSize(QSize(251, 31));
        question_1_2->setMouseTracking(true);
        question_1_2->setFrameShape(QFrame::Panel);
        question_1_2->setLineWidth(2);
        question_1_2->setMidLineWidth(1);
        question_1_2->setAlignment(Qt::AlignCenter);
        pushButton_1_6 = new QPushButton(simpleGame);
        pushButton_1_6->setObjectName(QStringLiteral("pushButton_1_6"));
        pushButton_1_6->setGeometry(QRect(180, 320, 271, 31));
        pushButton_1_6->setMinimumSize(QSize(231, 21));
        pushButton_1_6->setFont(font1);
        question_1_3 = new QLabel(simpleGame);
        question_1_3->setObjectName(QStringLiteral("question_1_3"));
        question_1_3->setEnabled(true);
        question_1_3->setGeometry(QRect(170, 130, 291, 51));
        question_1_3->setMinimumSize(QSize(251, 31));
        question_1_3->setMouseTracking(true);
        question_1_3->setFrameShape(QFrame::Panel);
        question_1_3->setLineWidth(2);
        question_1_3->setMidLineWidth(1);
        question_1_3->setAlignment(Qt::AlignCenter);
        question_1_6 = new QLabel(simpleGame);
        question_1_6->setObjectName(QStringLiteral("question_1_6"));
        question_1_6->setEnabled(true);
        question_1_6->setGeometry(QRect(171, 310, 291, 51));
        question_1_6->setMinimumSize(QSize(251, 31));
        question_1_6->setMouseTracking(true);
        question_1_6->setFrameShape(QFrame::Panel);
        question_1_6->setLineWidth(2);
        question_1_6->setMidLineWidth(1);
        question_1_6->setAlignment(Qt::AlignCenter);
        pushButton_1_2 = new QPushButton(simpleGame);
        pushButton_1_2->setObjectName(QStringLiteral("pushButton_1_2"));
        pushButton_1_2->setGeometry(QRect(179, 80, 271, 31));
        pushButton_1_2->setMinimumSize(QSize(231, 21));
        pushButton_1_2->setFont(font1);
        pushButton_1_3 = new QPushButton(simpleGame);
        pushButton_1_3->setObjectName(QStringLiteral("pushButton_1_3"));
        pushButton_1_3->setGeometry(QRect(179, 140, 271, 31));
        pushButton_1_3->setMinimumSize(QSize(231, 21));
        pushButton_1_3->setFont(font1);
        wrongButton_1_1 = new QPushButton(simpleGame);
        wrongButton_1_1->setObjectName(QStringLiteral("wrongButton_1_1"));
        wrongButton_1_1->setEnabled(true);
        wrongButton_1_1->setGeometry(QRect(59, 110, 81, 71));
        QIcon icon;
        icon.addFile(QStringLiteral(":/images/wrong_off.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon.addFile(QStringLiteral(":/images/wrong_on.png"), QSize(), QIcon::Normal, QIcon::On);
        icon.addFile(QStringLiteral(":/images/wrong_off.png"), QSize(), QIcon::Disabled, QIcon::Off);
        icon.addFile(QStringLiteral(":/images/wrong_off.png"), QSize(), QIcon::Active, QIcon::Off);
        icon.addFile(QStringLiteral(":/images/wrong_on.png"), QSize(), QIcon::Active, QIcon::On);
        icon.addFile(QStringLiteral(":/images/wrong_off.png"), QSize(), QIcon::Selected, QIcon::Off);
        wrongButton_1_1->setIcon(icon);
        wrongButton_1_1->setIconSize(QSize(81, 71));
        wrongButton_1_1->setCheckable(true);
        wrongButton_1_1->setAutoExclusive(false);
        wrongButton_1_1->setFlat(true);
        wrongButton_1_2 = new QPushButton(simpleGame);
        wrongButton_1_2->setObjectName(QStringLiteral("wrongButton_1_2"));
        wrongButton_1_2->setGeometry(QRect(59, 190, 81, 71));
        wrongButton_1_2->setIcon(icon);
        wrongButton_1_2->setIconSize(QSize(81, 71));
        wrongButton_1_2->setCheckable(true);
        wrongButton_1_2->setFlat(true);
        wrongButton_1_3 = new QPushButton(simpleGame);
        wrongButton_1_3->setObjectName(QStringLiteral("wrongButton_1_3"));
        wrongButton_1_3->setGeometry(QRect(59, 270, 81, 71));
        wrongButton_1_3->setIcon(icon);
        wrongButton_1_3->setIconSize(QSize(81, 71));
        wrongButton_1_3->setCheckable(true);
        wrongButton_1_3->setFlat(true);
        wrongButton_1_4 = new QPushButton(simpleGame);
        wrongButton_1_4->setObjectName(QStringLiteral("wrongButton_1_4"));
        wrongButton_1_4->setGeometry(QRect(489, 190, 81, 71));
        wrongButton_1_4->setIcon(icon);
        wrongButton_1_4->setIconSize(QSize(81, 71));
        wrongButton_1_4->setCheckable(true);
        wrongButton_1_4->setFlat(true);
        wrongButton_1_5 = new QPushButton(simpleGame);
        wrongButton_1_5->setObjectName(QStringLiteral("wrongButton_1_5"));
        wrongButton_1_5->setGeometry(QRect(489, 110, 81, 71));
        wrongButton_1_5->setIcon(icon);
        wrongButton_1_5->setIconSize(QSize(81, 71));
        wrongButton_1_5->setCheckable(true);
        wrongButton_1_5->setFlat(true);
        wrongButton_1_6 = new QPushButton(simpleGame);
        wrongButton_1_6->setObjectName(QStringLiteral("wrongButton_1_6"));
        wrongButton_1_6->setGeometry(QRect(489, 270, 81, 71));
        wrongButton_1_6->setIcon(icon);
        wrongButton_1_6->setIconSize(QSize(81, 71));
        wrongButton_1_6->setCheckable(true);
        wrongButton_1_6->setFlat(true);
        roundTable->addTab(simpleGame, QString());
        question_1_6->raise();
        question_1_4->raise();
        question_1_1->raise();
        pushButton_1_4->raise();
        question_1_5->raise();
        pushButton_1_1->raise();
        pushButton_1_5->raise();
        question_1_2->raise();
        pushButton_1_6->raise();
        question_1_3->raise();
        pushButton_1_2->raise();
        pushButton_1_3->raise();
        wrongButton_1_1->raise();
        wrongButton_1_2->raise();
        wrongButton_1_3->raise();
        wrongButton_1_4->raise();
        wrongButton_1_5->raise();
        wrongButton_1_6->raise();
        dubleGame = new QWidget();
        dubleGame->setObjectName(QStringLiteral("dubleGame"));
        dubleGame->setEnabled(true);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(dubleGame->sizePolicy().hasHeightForWidth());
        dubleGame->setSizePolicy(sizePolicy);
        question_2_6 = new QLabel(dubleGame);
        question_2_6->setObjectName(QStringLiteral("question_2_6"));
        question_2_6->setEnabled(true);
        question_2_6->setGeometry(QRect(172, 310, 291, 51));
        question_2_6->setMinimumSize(QSize(251, 31));
        question_2_6->setMouseTracking(true);
        question_2_6->setFrameShape(QFrame::Panel);
        question_2_6->setLineWidth(2);
        question_2_6->setMidLineWidth(1);
        question_2_6->setAlignment(Qt::AlignCenter);
        pushButton_2_4 = new QPushButton(dubleGame);
        pushButton_2_4->setObjectName(QStringLiteral("pushButton_2_4"));
        pushButton_2_4->setGeometry(QRect(181, 200, 271, 31));
        pushButton_2_4->setMinimumSize(QSize(231, 21));
        pushButton_2_4->setFont(font1);
        wrongButton_2_4 = new QPushButton(dubleGame);
        wrongButton_2_4->setObjectName(QStringLiteral("wrongButton_2_4"));
        wrongButton_2_4->setGeometry(QRect(60, 270, 81, 71));
        wrongButton_2_4->setIcon(icon);
        wrongButton_2_4->setIconSize(QSize(81, 71));
        wrongButton_2_4->setCheckable(true);
        wrongButton_2_4->setFlat(true);
        pushButton_2_6 = new QPushButton(dubleGame);
        pushButton_2_6->setObjectName(QStringLiteral("pushButton_2_6"));
        pushButton_2_6->setGeometry(QRect(181, 320, 271, 31));
        pushButton_2_6->setMinimumSize(QSize(231, 21));
        pushButton_2_6->setFont(font1);
        pushButton_2_2 = new QPushButton(dubleGame);
        pushButton_2_2->setObjectName(QStringLiteral("pushButton_2_2"));
        pushButton_2_2->setGeometry(QRect(180, 80, 271, 31));
        pushButton_2_2->setMinimumSize(QSize(231, 21));
        pushButton_2_2->setFont(font1);
        wrongButton_2_5 = new QPushButton(dubleGame);
        wrongButton_2_5->setObjectName(QStringLiteral("wrongButton_2_5"));
        wrongButton_2_5->setEnabled(true);
        wrongButton_2_5->setGeometry(QRect(60, 110, 81, 71));
        wrongButton_2_5->setIcon(icon);
        wrongButton_2_5->setIconSize(QSize(81, 71));
        wrongButton_2_5->setCheckable(true);
        wrongButton_2_5->setAutoExclusive(false);
        wrongButton_2_5->setFlat(true);
        pushButton_2_1 = new QPushButton(dubleGame);
        pushButton_2_1->setObjectName(QStringLiteral("pushButton_2_1"));
        pushButton_2_1->setGeometry(QRect(180, 20, 271, 31));
        pushButton_2_1->setMinimumSize(QSize(231, 21));
        pushButton_2_1->setFont(font1);
        question_2_5 = new QLabel(dubleGame);
        question_2_5->setObjectName(QStringLiteral("question_2_5"));
        question_2_5->setEnabled(true);
        question_2_5->setGeometry(QRect(172, 250, 291, 51));
        question_2_5->setMinimumSize(QSize(251, 31));
        question_2_5->setMouseTracking(true);
        question_2_5->setFrameShape(QFrame::Panel);
        question_2_5->setLineWidth(2);
        question_2_5->setMidLineWidth(1);
        question_2_5->setAlignment(Qt::AlignCenter);
        question_2_4 = new QLabel(dubleGame);
        question_2_4->setObjectName(QStringLiteral("question_2_4"));
        question_2_4->setEnabled(true);
        question_2_4->setGeometry(QRect(172, 190, 291, 51));
        question_2_4->setMinimumSize(QSize(251, 31));
        question_2_4->setMouseTracking(true);
        question_2_4->setFrameShape(QFrame::Panel);
        question_2_4->setLineWidth(2);
        question_2_4->setMidLineWidth(1);
        question_2_4->setAlignment(Qt::AlignCenter);
        wrongButton_2_6 = new QPushButton(dubleGame);
        wrongButton_2_6->setObjectName(QStringLiteral("wrongButton_2_6"));
        wrongButton_2_6->setGeometry(QRect(490, 270, 81, 71));
        wrongButton_2_6->setIcon(icon);
        wrongButton_2_6->setIconSize(QSize(81, 71));
        wrongButton_2_6->setCheckable(true);
        wrongButton_2_6->setFlat(true);
        wrongButton_2_1 = new QPushButton(dubleGame);
        wrongButton_2_1->setObjectName(QStringLiteral("wrongButton_2_1"));
        wrongButton_2_1->setGeometry(QRect(490, 190, 81, 71));
        wrongButton_2_1->setIcon(icon);
        wrongButton_2_1->setIconSize(QSize(81, 71));
        wrongButton_2_1->setCheckable(true);
        wrongButton_2_1->setFlat(true);
        pushButton_2_3 = new QPushButton(dubleGame);
        pushButton_2_3->setObjectName(QStringLiteral("pushButton_2_3"));
        pushButton_2_3->setGeometry(QRect(180, 140, 271, 31));
        pushButton_2_3->setMinimumSize(QSize(231, 21));
        pushButton_2_3->setFont(font1);
        question_2_1 = new QLabel(dubleGame);
        question_2_1->setObjectName(QStringLiteral("question_2_1"));
        question_2_1->setEnabled(true);
        question_2_1->setGeometry(QRect(171, 10, 291, 51));
        question_2_1->setMinimumSize(QSize(251, 31));
        question_2_1->setMouseTracking(true);
        question_2_1->setFrameShape(QFrame::Panel);
        question_2_1->setLineWidth(2);
        question_2_1->setMidLineWidth(1);
        question_2_1->setAlignment(Qt::AlignCenter);
        question_2_3 = new QLabel(dubleGame);
        question_2_3->setObjectName(QStringLiteral("question_2_3"));
        question_2_3->setEnabled(true);
        question_2_3->setGeometry(QRect(171, 130, 291, 51));
        question_2_3->setMinimumSize(QSize(251, 31));
        question_2_3->setMouseTracking(true);
        question_2_3->setFrameShape(QFrame::Panel);
        question_2_3->setLineWidth(2);
        question_2_3->setMidLineWidth(1);
        question_2_3->setAlignment(Qt::AlignCenter);
        wrongButton_2_2 = new QPushButton(dubleGame);
        wrongButton_2_2->setObjectName(QStringLiteral("wrongButton_2_2"));
        wrongButton_2_2->setGeometry(QRect(60, 190, 81, 71));
        wrongButton_2_2->setIcon(icon);
        wrongButton_2_2->setIconSize(QSize(81, 71));
        wrongButton_2_2->setCheckable(true);
        wrongButton_2_2->setFlat(true);
        wrongButton_2_3 = new QPushButton(dubleGame);
        wrongButton_2_3->setObjectName(QStringLiteral("wrongButton_2_3"));
        wrongButton_2_3->setGeometry(QRect(490, 110, 81, 71));
        wrongButton_2_3->setIcon(icon);
        wrongButton_2_3->setIconSize(QSize(81, 71));
        wrongButton_2_3->setCheckable(true);
        wrongButton_2_3->setFlat(true);
        question_2_2 = new QLabel(dubleGame);
        question_2_2->setObjectName(QStringLiteral("question_2_2"));
        question_2_2->setEnabled(true);
        question_2_2->setGeometry(QRect(171, 70, 291, 51));
        question_2_2->setMinimumSize(QSize(251, 31));
        question_2_2->setMouseTracking(true);
        question_2_2->setFrameShape(QFrame::Panel);
        question_2_2->setLineWidth(2);
        question_2_2->setMidLineWidth(1);
        question_2_2->setAlignment(Qt::AlignCenter);
        pushButton_2_5 = new QPushButton(dubleGame);
        pushButton_2_5->setObjectName(QStringLiteral("pushButton_2_5"));
        pushButton_2_5->setGeometry(QRect(181, 260, 271, 31));
        pushButton_2_5->setMinimumSize(QSize(231, 21));
        pushButton_2_5->setFont(font1);
        roundTable->addTab(dubleGame, QString());
        question_2_4->raise();
        question_2_3->raise();
        question_2_2->raise();
        question_2_1->raise();
        question_2_6->raise();
        pushButton_2_4->raise();
        wrongButton_2_4->raise();
        pushButton_2_6->raise();
        pushButton_2_2->raise();
        wrongButton_2_5->raise();
        pushButton_2_1->raise();
        question_2_5->raise();
        wrongButton_2_6->raise();
        wrongButton_2_1->raise();
        pushButton_2_3->raise();
        wrongButton_2_2->raise();
        wrongButton_2_3->raise();
        pushButton_2_5->raise();
        tripleGame = new QWidget();
        tripleGame->setObjectName(QStringLiteral("tripleGame"));
        question_3_6 = new QLabel(tripleGame);
        question_3_6->setObjectName(QStringLiteral("question_3_6"));
        question_3_6->setEnabled(true);
        question_3_6->setGeometry(QRect(172, 310, 291, 51));
        question_3_6->setMinimumSize(QSize(251, 31));
        question_3_6->setMouseTracking(true);
        question_3_6->setFrameShape(QFrame::Panel);
        question_3_6->setLineWidth(2);
        question_3_6->setMidLineWidth(1);
        question_3_6->setAlignment(Qt::AlignCenter);
        pushButton_3_4 = new QPushButton(tripleGame);
        pushButton_3_4->setObjectName(QStringLiteral("pushButton_3_4"));
        pushButton_3_4->setGeometry(QRect(181, 200, 271, 31));
        pushButton_3_4->setMinimumSize(QSize(231, 21));
        pushButton_3_4->setFont(font1);
        wrongButton_3_4 = new QPushButton(tripleGame);
        wrongButton_3_4->setObjectName(QStringLiteral("wrongButton_3_4"));
        wrongButton_3_4->setGeometry(QRect(60, 270, 81, 71));
        wrongButton_3_4->setIcon(icon);
        wrongButton_3_4->setIconSize(QSize(81, 71));
        wrongButton_3_4->setCheckable(true);
        wrongButton_3_4->setFlat(true);
        pushButton_3_6 = new QPushButton(tripleGame);
        pushButton_3_6->setObjectName(QStringLiteral("pushButton_3_6"));
        pushButton_3_6->setGeometry(QRect(181, 320, 271, 31));
        pushButton_3_6->setMinimumSize(QSize(231, 21));
        pushButton_3_6->setFont(font1);
        pushButton_3_2 = new QPushButton(tripleGame);
        pushButton_3_2->setObjectName(QStringLiteral("pushButton_3_2"));
        pushButton_3_2->setGeometry(QRect(180, 80, 271, 31));
        pushButton_3_2->setMinimumSize(QSize(231, 21));
        pushButton_3_2->setFont(font1);
        wrongButton_3_5 = new QPushButton(tripleGame);
        wrongButton_3_5->setObjectName(QStringLiteral("wrongButton_3_5"));
        wrongButton_3_5->setEnabled(true);
        wrongButton_3_5->setGeometry(QRect(60, 110, 81, 71));
        wrongButton_3_5->setIcon(icon);
        wrongButton_3_5->setIconSize(QSize(81, 71));
        wrongButton_3_5->setCheckable(true);
        wrongButton_3_5->setAutoExclusive(false);
        wrongButton_3_5->setFlat(true);
        pushButton_3_1 = new QPushButton(tripleGame);
        pushButton_3_1->setObjectName(QStringLiteral("pushButton_3_1"));
        pushButton_3_1->setGeometry(QRect(180, 20, 271, 31));
        pushButton_3_1->setMinimumSize(QSize(231, 21));
        pushButton_3_1->setFont(font1);
        question_3_5 = new QLabel(tripleGame);
        question_3_5->setObjectName(QStringLiteral("question_3_5"));
        question_3_5->setEnabled(true);
        question_3_5->setGeometry(QRect(172, 250, 291, 51));
        question_3_5->setMinimumSize(QSize(251, 31));
        question_3_5->setMouseTracking(true);
        question_3_5->setFrameShape(QFrame::Panel);
        question_3_5->setLineWidth(2);
        question_3_5->setMidLineWidth(1);
        question_3_5->setAlignment(Qt::AlignCenter);
        question_3_4 = new QLabel(tripleGame);
        question_3_4->setObjectName(QStringLiteral("question_3_4"));
        question_3_4->setEnabled(true);
        question_3_4->setGeometry(QRect(172, 190, 291, 51));
        question_3_4->setMinimumSize(QSize(251, 31));
        question_3_4->setMouseTracking(true);
        question_3_4->setFrameShape(QFrame::Panel);
        question_3_4->setLineWidth(2);
        question_3_4->setMidLineWidth(1);
        question_3_4->setAlignment(Qt::AlignCenter);
        wrongButton_3_6 = new QPushButton(tripleGame);
        wrongButton_3_6->setObjectName(QStringLiteral("wrongButton_3_6"));
        wrongButton_3_6->setGeometry(QRect(490, 270, 81, 71));
        wrongButton_3_6->setIcon(icon);
        wrongButton_3_6->setIconSize(QSize(81, 71));
        wrongButton_3_6->setCheckable(true);
        wrongButton_3_6->setFlat(true);
        wrongButton_3_1 = new QPushButton(tripleGame);
        wrongButton_3_1->setObjectName(QStringLiteral("wrongButton_3_1"));
        wrongButton_3_1->setGeometry(QRect(490, 190, 81, 71));
        wrongButton_3_1->setIcon(icon);
        wrongButton_3_1->setIconSize(QSize(81, 71));
        wrongButton_3_1->setCheckable(true);
        wrongButton_3_1->setFlat(true);
        pushButton_3_3 = new QPushButton(tripleGame);
        pushButton_3_3->setObjectName(QStringLiteral("pushButton_3_3"));
        pushButton_3_3->setGeometry(QRect(180, 140, 271, 31));
        pushButton_3_3->setMinimumSize(QSize(231, 21));
        pushButton_3_3->setFont(font1);
        question_3_1 = new QLabel(tripleGame);
        question_3_1->setObjectName(QStringLiteral("question_3_1"));
        question_3_1->setEnabled(true);
        question_3_1->setGeometry(QRect(171, 10, 291, 51));
        question_3_1->setMinimumSize(QSize(251, 31));
        question_3_1->setMouseTracking(true);
        question_3_1->setFrameShape(QFrame::Panel);
        question_3_1->setLineWidth(2);
        question_3_1->setMidLineWidth(1);
        question_3_1->setAlignment(Qt::AlignCenter);
        question_3_3 = new QLabel(tripleGame);
        question_3_3->setObjectName(QStringLiteral("question_3_3"));
        question_3_3->setEnabled(true);
        question_3_3->setGeometry(QRect(171, 130, 291, 51));
        question_3_3->setMinimumSize(QSize(251, 31));
        question_3_3->setMouseTracking(true);
        question_3_3->setFrameShape(QFrame::Panel);
        question_3_3->setLineWidth(2);
        question_3_3->setMidLineWidth(1);
        question_3_3->setAlignment(Qt::AlignCenter);
        wrongButton_3_2 = new QPushButton(tripleGame);
        wrongButton_3_2->setObjectName(QStringLiteral("wrongButton_3_2"));
        wrongButton_3_2->setGeometry(QRect(60, 190, 81, 71));
        wrongButton_3_2->setIcon(icon);
        wrongButton_3_2->setIconSize(QSize(81, 71));
        wrongButton_3_2->setCheckable(true);
        wrongButton_3_2->setFlat(true);
        wrongButton_3_3 = new QPushButton(tripleGame);
        wrongButton_3_3->setObjectName(QStringLiteral("wrongButton_3_3"));
        wrongButton_3_3->setGeometry(QRect(490, 110, 81, 71));
        wrongButton_3_3->setIcon(icon);
        wrongButton_3_3->setIconSize(QSize(81, 71));
        wrongButton_3_3->setCheckable(true);
        wrongButton_3_3->setFlat(true);
        question_3_2 = new QLabel(tripleGame);
        question_3_2->setObjectName(QStringLiteral("question_3_2"));
        question_3_2->setEnabled(true);
        question_3_2->setGeometry(QRect(171, 70, 291, 51));
        question_3_2->setMinimumSize(QSize(251, 31));
        question_3_2->setMouseTracking(true);
        question_3_2->setFrameShape(QFrame::Panel);
        question_3_2->setLineWidth(2);
        question_3_2->setMidLineWidth(1);
        question_3_2->setAlignment(Qt::AlignCenter);
        pushButton_3_5 = new QPushButton(tripleGame);
        pushButton_3_5->setObjectName(QStringLiteral("pushButton_3_5"));
        pushButton_3_5->setGeometry(QRect(181, 260, 271, 31));
        pushButton_3_5->setMinimumSize(QSize(231, 21));
        pushButton_3_5->setFont(font1);
        roundTable->addTab(tripleGame, QString());
        question_3_4->raise();
        question_3_3->raise();
        question_3_1->raise();
        question_3_2->raise();
        question_3_6->raise();
        pushButton_3_4->raise();
        wrongButton_3_4->raise();
        pushButton_3_6->raise();
        pushButton_3_2->raise();
        wrongButton_3_5->raise();
        pushButton_3_1->raise();
        question_3_5->raise();
        wrongButton_3_6->raise();
        wrongButton_3_1->raise();
        pushButton_3_3->raise();
        wrongButton_3_2->raise();
        wrongButton_3_3->raise();
        pushButton_3_5->raise();
        reversGame = new QWidget();
        reversGame->setObjectName(QStringLiteral("reversGame"));
        question_4_6 = new QLabel(reversGame);
        question_4_6->setObjectName(QStringLiteral("question_4_6"));
        question_4_6->setEnabled(true);
        question_4_6->setGeometry(QRect(171, 310, 291, 51));
        question_4_6->setMinimumSize(QSize(251, 31));
        question_4_6->setMouseTracking(true);
        question_4_6->setFrameShape(QFrame::Panel);
        question_4_6->setLineWidth(2);
        question_4_6->setMidLineWidth(1);
        question_4_6->setAlignment(Qt::AlignCenter);
        pushButton_4_4 = new QPushButton(reversGame);
        pushButton_4_4->setObjectName(QStringLiteral("pushButton_4_4"));
        pushButton_4_4->setGeometry(QRect(180, 200, 271, 31));
        pushButton_4_4->setMinimumSize(QSize(231, 21));
        pushButton_4_4->setFont(font1);
        wrongButton_4_4 = new QPushButton(reversGame);
        wrongButton_4_4->setObjectName(QStringLiteral("wrongButton_4_4"));
        wrongButton_4_4->setGeometry(QRect(59, 270, 81, 71));
        wrongButton_4_4->setIcon(icon);
        wrongButton_4_4->setIconSize(QSize(81, 71));
        wrongButton_4_4->setCheckable(true);
        wrongButton_4_4->setFlat(true);
        pushButton_4_6 = new QPushButton(reversGame);
        pushButton_4_6->setObjectName(QStringLiteral("pushButton_4_6"));
        pushButton_4_6->setGeometry(QRect(180, 320, 271, 31));
        pushButton_4_6->setMinimumSize(QSize(231, 21));
        pushButton_4_6->setFont(font1);
        pushButton_4_2 = new QPushButton(reversGame);
        pushButton_4_2->setObjectName(QStringLiteral("pushButton_4_2"));
        pushButton_4_2->setGeometry(QRect(179, 80, 271, 31));
        pushButton_4_2->setMinimumSize(QSize(231, 21));
        pushButton_4_2->setFont(font1);
        wrongButton_4_5 = new QPushButton(reversGame);
        wrongButton_4_5->setObjectName(QStringLiteral("wrongButton_4_5"));
        wrongButton_4_5->setEnabled(true);
        wrongButton_4_5->setGeometry(QRect(59, 110, 81, 71));
        wrongButton_4_5->setIcon(icon);
        wrongButton_4_5->setIconSize(QSize(81, 71));
        wrongButton_4_5->setCheckable(true);
        wrongButton_4_5->setAutoExclusive(false);
        wrongButton_4_5->setFlat(true);
        pushButton_4_1 = new QPushButton(reversGame);
        pushButton_4_1->setObjectName(QStringLiteral("pushButton_4_1"));
        pushButton_4_1->setGeometry(QRect(179, 20, 271, 31));
        pushButton_4_1->setMinimumSize(QSize(231, 21));
        pushButton_4_1->setFont(font1);
        question_4_5 = new QLabel(reversGame);
        question_4_5->setObjectName(QStringLiteral("question_4_5"));
        question_4_5->setEnabled(true);
        question_4_5->setGeometry(QRect(171, 250, 291, 51));
        question_4_5->setMinimumSize(QSize(251, 31));
        question_4_5->setMouseTracking(true);
        question_4_5->setFrameShape(QFrame::Panel);
        question_4_5->setLineWidth(2);
        question_4_5->setMidLineWidth(1);
        question_4_5->setAlignment(Qt::AlignCenter);
        question_4_4 = new QLabel(reversGame);
        question_4_4->setObjectName(QStringLiteral("question_4_4"));
        question_4_4->setEnabled(true);
        question_4_4->setGeometry(QRect(171, 190, 291, 51));
        question_4_4->setMinimumSize(QSize(251, 31));
        question_4_4->setMouseTracking(true);
        question_4_4->setFrameShape(QFrame::Panel);
        question_4_4->setLineWidth(2);
        question_4_4->setMidLineWidth(1);
        question_4_4->setAlignment(Qt::AlignCenter);
        wrongButton_4_6 = new QPushButton(reversGame);
        wrongButton_4_6->setObjectName(QStringLiteral("wrongButton_4_6"));
        wrongButton_4_6->setGeometry(QRect(489, 270, 81, 71));
        wrongButton_4_6->setIcon(icon);
        wrongButton_4_6->setIconSize(QSize(81, 71));
        wrongButton_4_6->setCheckable(true);
        wrongButton_4_6->setFlat(true);
        wrongButton_4_1 = new QPushButton(reversGame);
        wrongButton_4_1->setObjectName(QStringLiteral("wrongButton_4_1"));
        wrongButton_4_1->setGeometry(QRect(489, 190, 81, 71));
        wrongButton_4_1->setIcon(icon);
        wrongButton_4_1->setIconSize(QSize(81, 71));
        wrongButton_4_1->setCheckable(true);
        wrongButton_4_1->setFlat(true);
        pushButton_4_3 = new QPushButton(reversGame);
        pushButton_4_3->setObjectName(QStringLiteral("pushButton_4_3"));
        pushButton_4_3->setGeometry(QRect(179, 140, 271, 31));
        pushButton_4_3->setMinimumSize(QSize(231, 21));
        pushButton_4_3->setFont(font1);
        question_4_1 = new QLabel(reversGame);
        question_4_1->setObjectName(QStringLiteral("question_4_1"));
        question_4_1->setEnabled(true);
        question_4_1->setGeometry(QRect(170, 10, 291, 51));
        question_4_1->setMinimumSize(QSize(251, 31));
        question_4_1->setMouseTracking(true);
        question_4_1->setFrameShape(QFrame::Panel);
        question_4_1->setLineWidth(2);
        question_4_1->setMidLineWidth(1);
        question_4_1->setAlignment(Qt::AlignCenter);
        question_4_3 = new QLabel(reversGame);
        question_4_3->setObjectName(QStringLiteral("question_4_3"));
        question_4_3->setEnabled(true);
        question_4_3->setGeometry(QRect(170, 130, 291, 51));
        question_4_3->setMinimumSize(QSize(251, 31));
        question_4_3->setMouseTracking(true);
        question_4_3->setFrameShape(QFrame::Panel);
        question_4_3->setLineWidth(2);
        question_4_3->setMidLineWidth(1);
        question_4_3->setAlignment(Qt::AlignCenter);
        wrongButton_4_2 = new QPushButton(reversGame);
        wrongButton_4_2->setObjectName(QStringLiteral("wrongButton_4_2"));
        wrongButton_4_2->setGeometry(QRect(59, 190, 81, 71));
        wrongButton_4_2->setIcon(icon);
        wrongButton_4_2->setIconSize(QSize(81, 71));
        wrongButton_4_2->setCheckable(true);
        wrongButton_4_2->setFlat(true);
        wrongButton_4_3 = new QPushButton(reversGame);
        wrongButton_4_3->setObjectName(QStringLiteral("wrongButton_4_3"));
        wrongButton_4_3->setGeometry(QRect(489, 110, 81, 71));
        wrongButton_4_3->setIcon(icon);
        wrongButton_4_3->setIconSize(QSize(81, 71));
        wrongButton_4_3->setCheckable(true);
        wrongButton_4_3->setFlat(true);
        question_4_2 = new QLabel(reversGame);
        question_4_2->setObjectName(QStringLiteral("question_4_2"));
        question_4_2->setEnabled(true);
        question_4_2->setGeometry(QRect(170, 70, 291, 51));
        question_4_2->setMinimumSize(QSize(251, 31));
        question_4_2->setMouseTracking(true);
        question_4_2->setFrameShape(QFrame::Panel);
        question_4_2->setLineWidth(2);
        question_4_2->setMidLineWidth(1);
        question_4_2->setAlignment(Qt::AlignCenter);
        pushButton_4_5 = new QPushButton(reversGame);
        pushButton_4_5->setObjectName(QStringLiteral("pushButton_4_5"));
        pushButton_4_5->setGeometry(QRect(180, 260, 271, 31));
        pushButton_4_5->setMinimumSize(QSize(231, 21));
        pushButton_4_5->setFont(font1);
        roundTable->addTab(reversGame, QString());
        question_4_4->raise();
        question_4_1->raise();
        question_4_2->raise();
        question_4_3->raise();
        question_4_6->raise();
        pushButton_4_4->raise();
        wrongButton_4_4->raise();
        pushButton_4_6->raise();
        pushButton_4_2->raise();
        wrongButton_4_5->raise();
        pushButton_4_1->raise();
        question_4_5->raise();
        wrongButton_4_6->raise();
        wrongButton_4_1->raise();
        pushButton_4_3->raise();
        wrongButton_4_2->raise();
        wrongButton_4_3->raise();
        pushButton_4_5->raise();
        MainWindow->setCentralWidget(gameTable);
        roundTable->raise();
        gameName->raise();

        retranslateUi(MainWindow);

        roundTable->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        gameName->setText(QApplication::translate("MainWindow", "100 vs 1", nullptr));
        label->setText(QApplication::translate("MainWindow", "\320\241\321\207\320\270\321\202\320\260\321\202\321\214 \321\204\320\260\320\271\320\273", nullptr));
        dialogReadButton->setText(QApplication::translate("MainWindow", "\320\222\321\213\320\261\321\200\320\260\321\202\321\214", nullptr));
        readButton->setText(QApplication::translate("MainWindow", "\320\241\321\207\320\270\321\202\320\260\321\202\321\214", nullptr));
        roundTable->setTabText(roundTable->indexOf(start_page), QApplication::translate("MainWindow", "\320\222\321\213\320\261\320\276\321\200 \320\270\320\263\321\200\321\213", nullptr));
        pushButton_1_4->setText(QApplication::translate("MainWindow", "4", nullptr));
        pushButton_1_1->setText(QApplication::translate("MainWindow", "1", nullptr));
        pushButton_1_5->setText(QApplication::translate("MainWindow", "5", nullptr));
        pushButton_1_6->setText(QApplication::translate("MainWindow", "6", nullptr));
        pushButton_1_2->setText(QApplication::translate("MainWindow", "2", nullptr));
        pushButton_1_3->setText(QApplication::translate("MainWindow", "3", nullptr));
        wrongButton_1_1->setText(QString());
        wrongButton_1_2->setText(QString());
        wrongButton_1_3->setText(QString());
        wrongButton_1_4->setText(QString());
        wrongButton_1_5->setText(QString());
        wrongButton_1_6->setText(QString());
        roundTable->setTabText(roundTable->indexOf(simpleGame), QApplication::translate("MainWindow", "\320\237\321\200\320\276\321\201\321\202\320\260\321\217 \320\270\320\263\321\200\320\260", nullptr));
        pushButton_2_4->setText(QApplication::translate("MainWindow", "4", nullptr));
        wrongButton_2_4->setText(QString());
        pushButton_2_6->setText(QApplication::translate("MainWindow", "6", nullptr));
        pushButton_2_2->setText(QApplication::translate("MainWindow", "2", nullptr));
        wrongButton_2_5->setText(QString());
        pushButton_2_1->setText(QApplication::translate("MainWindow", "1", nullptr));
        wrongButton_2_6->setText(QString());
        wrongButton_2_1->setText(QString());
        pushButton_2_3->setText(QApplication::translate("MainWindow", "3", nullptr));
        wrongButton_2_2->setText(QString());
        wrongButton_2_3->setText(QString());
        pushButton_2_5->setText(QApplication::translate("MainWindow", "5", nullptr));
        roundTable->setTabText(roundTable->indexOf(dubleGame), QApplication::translate("MainWindow", "\320\224\320\262\320\276\320\271\320\275\320\260\321\217 \320\270\320\263\321\200\320\260", nullptr));
        pushButton_3_4->setText(QApplication::translate("MainWindow", "4", nullptr));
        wrongButton_3_4->setText(QString());
        pushButton_3_6->setText(QApplication::translate("MainWindow", "6", nullptr));
        pushButton_3_2->setText(QApplication::translate("MainWindow", "2", nullptr));
        wrongButton_3_5->setText(QString());
        pushButton_3_1->setText(QApplication::translate("MainWindow", "1", nullptr));
        wrongButton_3_6->setText(QString());
        wrongButton_3_1->setText(QString());
        pushButton_3_3->setText(QApplication::translate("MainWindow", "3", nullptr));
        wrongButton_3_2->setText(QString());
        wrongButton_3_3->setText(QString());
        pushButton_3_5->setText(QApplication::translate("MainWindow", "5", nullptr));
        roundTable->setTabText(roundTable->indexOf(tripleGame), QApplication::translate("MainWindow", "\320\242\321\200\320\276\320\271\320\275\320\260\321\217 \320\270\320\263\321\200\320\260", nullptr));
        pushButton_4_4->setText(QApplication::translate("MainWindow", "4", nullptr));
        wrongButton_4_4->setText(QString());
        pushButton_4_6->setText(QApplication::translate("MainWindow", "6", nullptr));
        pushButton_4_2->setText(QApplication::translate("MainWindow", "2", nullptr));
        wrongButton_4_5->setText(QString());
        pushButton_4_1->setText(QApplication::translate("MainWindow", "1", nullptr));
        wrongButton_4_6->setText(QString());
        wrongButton_4_1->setText(QString());
        pushButton_4_3->setText(QApplication::translate("MainWindow", "3", nullptr));
        wrongButton_4_2->setText(QString());
        wrongButton_4_3->setText(QString());
        pushButton_4_5->setText(QApplication::translate("MainWindow", "5", nullptr));
        roundTable->setTabText(roundTable->indexOf(reversGame), QApplication::translate("MainWindow", "\320\230\320\263\321\200\320\260 \320\275\320\260\320\276\320\261\320\276\321\200\320\276\321\202", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
